name: Build documentation
on: [push]
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          
      - name: Build docs
        uses: andstor/jsdoc-action@v1
        with: 
          source_dir: ./js
          recurse: true
          output_dir: ./docs
          config_file: ./conf.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs